/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui_Calculator;

/**
 *
 * @author AhmedTalal
 */
public class Calculator_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Calculator_JFrame
     */
     public int FirstNumber;
      public int LastNumber;
     public int Result;
     public String operation;
     public String iNum;
       private Object math;
    public Calculator_JFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Display_TextField1 = new javax.swing.JTextField();
        Back_Button1 = new javax.swing.JButton();
        C_Button2 = new javax.swing.JButton();
        jButton_gazer = new javax.swing.JButton();
        Button_9 = new javax.swing.JButton();
        Button_8 = new javax.swing.JButton();
        Button_7 = new javax.swing.JButton();
        Button_6 = new javax.swing.JButton();
        Button_4 = new javax.swing.JButton();
        Button_5 = new javax.swing.JButton();
        Button_3 = new javax.swing.JButton();
        Button_2 = new javax.swing.JButton();
        Button_1 = new javax.swing.JButton();
        Button_Zero = new javax.swing.JButton();
        Button_Equal = new javax.swing.JButton();
        Button_Sum = new javax.swing.JButton();
        Button_Remandeer = new javax.swing.JButton();
        Button_Minus = new javax.swing.JButton();
        Button_Multi = new javax.swing.JButton();
        Button_Devision = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        File_Menu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CalcApp");

        Display_TextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Back_Button1.setBackground(new java.awt.Color(242, 38, 19));
        Back_Button1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Back_Button1.setText("->");
        Back_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_Button1ActionPerformed(evt);
            }
        });

        C_Button2.setBackground(new java.awt.Color(242, 38, 19));
        C_Button2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        C_Button2.setText("c");
        C_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_Button2ActionPerformed(evt);
            }
        });

        jButton_gazer.setBackground(new java.awt.Color(242, 38, 19));
        jButton_gazer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_gazer.setText("√");
        jButton_gazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gazerActionPerformed(evt);
            }
        });

        Button_9.setBackground(new java.awt.Color(242, 38, 19));
        Button_9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_9.setText("9");
        Button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_9ActionPerformed(evt);
            }
        });

        Button_8.setBackground(new java.awt.Color(242, 38, 19));
        Button_8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_8.setText("8");
        Button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_8ActionPerformed(evt);
            }
        });

        Button_7.setBackground(new java.awt.Color(242, 38, 19));
        Button_7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_7.setText("7");
        Button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_7ActionPerformed(evt);
            }
        });

        Button_6.setBackground(new java.awt.Color(242, 38, 19));
        Button_6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_6.setText("6");
        Button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_6ActionPerformed(evt);
            }
        });

        Button_4.setBackground(new java.awt.Color(242, 38, 19));
        Button_4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_4.setText("4");
        Button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_4ActionPerformed(evt);
            }
        });

        Button_5.setBackground(new java.awt.Color(242, 38, 19));
        Button_5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_5.setText("5");
        Button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_5ActionPerformed(evt);
            }
        });

        Button_3.setBackground(new java.awt.Color(242, 38, 19));
        Button_3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_3.setText("3");
        Button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3ActionPerformed(evt);
            }
        });

        Button_2.setBackground(new java.awt.Color(242, 38, 19));
        Button_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_2.setText("2");
        Button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2ActionPerformed(evt);
            }
        });

        Button_1.setBackground(new java.awt.Color(242, 38, 19));
        Button_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_1.setText("1");
        Button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_1ActionPerformed(evt);
            }
        });

        Button_Zero.setBackground(new java.awt.Color(242, 38, 19));
        Button_Zero.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_Zero.setText("0");
        Button_Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ZeroActionPerformed(evt);
            }
        });

        Button_Equal.setBackground(new java.awt.Color(242, 38, 19));
        Button_Equal.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        Button_Equal.setText("=");
        Button_Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EqualActionPerformed(evt);
            }
        });

        Button_Sum.setBackground(new java.awt.Color(242, 38, 19));
        Button_Sum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_Sum.setText("+");
        Button_Sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SumActionPerformed(evt);
            }
        });

        Button_Remandeer.setBackground(new java.awt.Color(242, 38, 19));
        Button_Remandeer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_Remandeer.setText("%");
        Button_Remandeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RemandeerActionPerformed(evt);
            }
        });

        Button_Minus.setBackground(new java.awt.Color(242, 38, 19));
        Button_Minus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_Minus.setText("-");
        Button_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MinusActionPerformed(evt);
            }
        });

        Button_Multi.setBackground(new java.awt.Color(242, 38, 19));
        Button_Multi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_Multi.setText("*");
        Button_Multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MultiActionPerformed(evt);
            }
        });

        Button_Devision.setBackground(new java.awt.Color(242, 38, 19));
        Button_Devision.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Button_Devision.setText("/");
        Button_Devision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DevisionActionPerformed(evt);
            }
        });

        File_Menu1.setText("File");
        File_Menu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem1.setText("Scientific");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        File_Menu1.add(jMenuItem1);

        jMenuBar1.add(File_Menu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Display_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(Button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(Button_Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Button_Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(Button_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addComponent(Button_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(Button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(Button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(Button_Devision, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Back_Button1)
                                .addGap(38, 38, 38)
                                .addComponent(C_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton_gazer, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(Button_Remandeer, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(Button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(Button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(Button_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Display_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back_Button1)
                    .addComponent(C_Button2)
                    .addComponent(jButton_gazer)
                    .addComponent(Button_Remandeer))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_9)
                    .addComponent(Button_8)
                    .addComponent(Button_7)
                    .addComponent(Button_Multi))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_6)
                    .addComponent(Button_5)
                    .addComponent(Button_4)
                    .addComponent(Button_Devision))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_3)
                    .addComponent(Button_2)
                    .addComponent(Button_1)
                    .addComponent(Button_Minus))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Button_Zero))
                    .addComponent(Button_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(Button_Sum)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_Button2ActionPerformed
        // TODO add your handling code here:
        Display_TextField1.setText("");
    }//GEN-LAST:event_C_Button2ActionPerformed

    private void Button_DevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DevisionActionPerformed
        // TODO add your handling code here:
        FirstNumber =  Integer.parseInt(Display_TextField1.getText());
        Display_TextField1.setText(null);
        operation = "/";
    }//GEN-LAST:event_Button_DevisionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Scientific_Claculator_frame Scien = new Scientific_Claculator_frame();
        this.setVisible(false);
        Scien.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Back_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_Button1ActionPerformed
        // TODO add your handling code here:
         String bsp = null;
        if(Display_TextField1.getText().length() > 0)
        {
            StringBuilder strB =  new StringBuilder(Display_TextField1.getText());
            strB.deleteCharAt(Display_TextField1.getText().length() -1 );
            bsp = strB.toString();
            Display_TextField1.setText(bsp);
        }
    }//GEN-LAST:event_Back_Button1ActionPerformed

    private void Button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_9ActionPerformed
        // TODO add your handling code here:
         iNum =  Display_TextField1.getText() + Button_9.getText();
        Display_TextField1.setText(iNum);
    }//GEN-LAST:event_Button_9ActionPerformed

    private void Button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_8ActionPerformed
        // TODO add your handling code here:
         iNum =  Display_TextField1.getText() + Button_8.getText();
        Display_TextField1.setText(iNum);
    }//GEN-LAST:event_Button_8ActionPerformed

    private void Button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_7ActionPerformed
        // TODO add your handling code here:
          iNum =  Display_TextField1.getText() + Button_7.getText();
        Display_TextField1.setText(iNum);
    }//GEN-LAST:event_Button_7ActionPerformed

    private void Button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_6ActionPerformed
        // TODO add your handling code here:
          iNum =  Display_TextField1.getText() + Button_6.getText();
        Display_TextField1.setText(iNum);
    }//GEN-LAST:event_Button_6ActionPerformed

    private void Button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_5ActionPerformed
        // TODO add your handling code here:
         iNum =  Display_TextField1.getText() + Button_5.getText();
        Display_TextField1.setText(iNum);
    }//GEN-LAST:event_Button_5ActionPerformed

    private void Button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_4ActionPerformed
        // TODO add your handling code here:
         iNum =  Display_TextField1.getText() + Button_4.getText();
        Display_TextField1.setText(iNum);
    }//GEN-LAST:event_Button_4ActionPerformed

    private void Button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_3ActionPerformed
        // TODO add your handling code here:
         iNum =  Display_TextField1.getText() + Button_3.getText();
        Display_TextField1.setText(iNum);
    }//GEN-LAST:event_Button_3ActionPerformed

    private void Button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_2ActionPerformed
        // TODO add your handling code here:
          iNum =  Display_TextField1.getText() + Button_2.getText();
        Display_TextField1.setText(iNum);
    }//GEN-LAST:event_Button_2ActionPerformed

    private void Button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_1ActionPerformed
        // TODO add your handling code here:
         iNum =  Display_TextField1.getText() + Button_1.getText();
        Display_TextField1.setText(iNum);
    }//GEN-LAST:event_Button_1ActionPerformed

    private void Button_ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ZeroActionPerformed
        // TODO add your handling code here:
        iNum =  Display_TextField1.getText() + Button_Zero.getText();
        Display_TextField1.setText(iNum);
    }//GEN-LAST:event_Button_ZeroActionPerformed

    private void Button_RemandeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RemandeerActionPerformed
        // TODO add your handling code here:
        FirstNumber =  Integer.parseInt(Display_TextField1.getText());
        Display_TextField1.setText(null);
        operation = "%";
    }//GEN-LAST:event_Button_RemandeerActionPerformed

    private void Button_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MultiActionPerformed
        // TODO add your handling code here:
         FirstNumber =  Integer.parseInt(Display_TextField1.getText());
        Display_TextField1.setText(null);
        operation = "*";
    }//GEN-LAST:event_Button_MultiActionPerformed

    private void Button_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MinusActionPerformed
        // TODO add your handling code here:
         FirstNumber =  Integer.parseInt(Display_TextField1.getText());
        Display_TextField1.setText(null);
        operation = "-";
    }//GEN-LAST:event_Button_MinusActionPerformed

    private void Button_SumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SumActionPerformed
        // TODO add your handling code here:
         FirstNumber =  Integer.parseInt(Display_TextField1.getText());
        operation = "+";
        Display_TextField1.setText(null);
       
    }//GEN-LAST:event_Button_SumActionPerformed

    private void Button_EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EqualActionPerformed
        // TODO add your handling code here:
         LastNumber =  Integer.parseInt(Display_TextField1.getText()); 
        switch(operation){
            case "+":
                Result = FirstNumber + LastNumber;
                Display_TextField1.setText(String.valueOf(Result));
                break;
            case "-":
                Result = FirstNumber - LastNumber;
                Display_TextField1.setText(String.valueOf(Result));
                break;
            case "*":
                Result = FirstNumber * LastNumber;
                Display_TextField1.setText(String.valueOf(Result));
                break;
            case "/":
                if(LastNumber == 0){
                    Display_TextField1.setText("Math error!");
                }else{
                Result = FirstNumber / LastNumber;
                Display_TextField1.setText(String.valueOf(Result));
                }
                break;
            case "%":
                Result = FirstNumber % LastNumber;
                Display_TextField1.setText(String.valueOf(Result));
                break;
            case "√":
               
                Display_TextField1.setText(String.valueOf(Math.sqrt(LastNumber)));
                
               default:
                   Display_TextField1.setText("No operation!");
                
        }
    }//GEN-LAST:event_Button_EqualActionPerformed

    private void jButton_gazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gazerActionPerformed
        // TODO add your handling code here:
      double  ops = Double.parseDouble(String .valueOf(Display_TextField1.getText()));
        ops =  Math.sqrt(ops);
         Display_TextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButton_gazerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button1;
    private javax.swing.JButton Button_1;
    private javax.swing.JButton Button_2;
    private javax.swing.JButton Button_3;
    private javax.swing.JButton Button_4;
    private javax.swing.JButton Button_5;
    private javax.swing.JButton Button_6;
    private javax.swing.JButton Button_7;
    private javax.swing.JButton Button_8;
    private javax.swing.JButton Button_9;
    private javax.swing.JButton Button_Devision;
    private javax.swing.JButton Button_Equal;
    private javax.swing.JButton Button_Minus;
    private javax.swing.JButton Button_Multi;
    private javax.swing.JButton Button_Remandeer;
    private javax.swing.JButton Button_Sum;
    private javax.swing.JButton Button_Zero;
    private javax.swing.JButton C_Button2;
    private javax.swing.JTextField Display_TextField1;
    private javax.swing.JMenu File_Menu1;
    private javax.swing.JButton jButton_gazer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
